### ISSUE TITLE
converting h5 to hic or cool format

### ISSUE THREAD

**Issue by papelypluma** [LeopoldC/Boost-HiC#3]
Hi @LeopoldC. Thank you for sharing this tool. I'd like to ask if there's a way to convert the h5 output matrix to hic or cool format. I've so far tried hicConvertFormat, but it's not working.

Thank you.

**Comment by LeopoldC** [comment]
Hi papelypluma.
There is no direct way to convert to .hic or .cool on the actual code. I think the best way is to save matrix as text .hicpro format   (parsing sounds easy to do ) and from this point you can go at every format you like.

**Comment by LeopoldC** [comment]
[saveasmatrix.txt](https://github.com/LeopoldC/Boost-HiC/files/7660471/saveasmatrix.txt)

Here a function that will allow you to write as .matrix for HiCpro format the result, add it into the code, and then you will be abble from HiCpro format to go to HiC or cool as you need.

Hope that it help.

**Comment by papelypluma** [comment]
Hi @LeopoldC, thank you for sharing this one! I'd just like to confirm that this user-defined function should go into the HiCutils.py, then call this function in the main.py to save the matrix as a hicpro-formatted text file in addition to h5 output that's already in the main.py script.

Thank you!

**Comment by LeopoldC** [comment]
You have my confirmation :).

I write it right after seeing your comment.
