### ISSUE TITLE
main.py:26: RuntimeWarning: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by papelypluma** [LeopoldC/Boost-HiC#4]
Hi @LeopoldC. While running Boost-HiC, the following warning is encountered, although the job is still running. I'm wondering if this is something one has to worry about, since the analysis has been running for almost 2 days with only filteredbin.txt,  inputmat_filtered.hdf5 and  inputmat.hdf5 in the output directory. 

> main.py:26: RuntimeWarning: divide by zero encountered in true_divide
>   FFmat=np.power(HiCutils.fastFloyd(1/np.power(normmat.copy(),alpha)),-1/alpha) #to dist, FF, to contact in one line

Thank you.

**Comment by LeopoldC** [comment]
no worries to have :)
